package udp_demo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: req.proto

public final class Req {
  private Req() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqPkgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqPkg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ReqPkg.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .ReqPkg.Header header = 1;</code>
     */
    Req.ReqPkg.Header getHeader();
    /**
     * <code>required .ReqPkg.Header header = 1;</code>
     */
    Req.ReqPkg.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>required bytes reqinfo = 2;</code>
     *
     * <pre>
     *AES���ܺ��ReqInfo
     * </pre>
     */
    boolean hasReqinfo();
    /**
     * <code>required bytes reqinfo = 2;</code>
     *
     * <pre>
     *AES���ܺ��ReqInfo
     * </pre>
     */
    com.google.protobuf.ByteString getReqinfo();
  }
  /**
   * Protobuf type {@code ReqPkg}
   */
  public static final class ReqPkg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqPkg)
      ReqPkgOrBuilder {
    // Use ReqPkg.newBuilder() to construct.
    private ReqPkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqPkg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqPkg defaultInstance;
    public static ReqPkg getDefaultInstance() {
      return defaultInstance;
    }

    public ReqPkg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqPkg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Req.ReqPkg.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Req.ReqPkg.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reqinfo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Req.internal_static_ReqPkg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Req.internal_static_ReqPkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Req.ReqPkg.class, Req.ReqPkg.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqPkg> PARSER =
        new com.google.protobuf.AbstractParser<ReqPkg>() {
      public ReqPkg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqPkg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqPkg> getParserForType() {
      return PARSER;
    }

    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ReqPkg.Header)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 appid = 1;</code>
       */
      boolean hasAppid();
      /**
       * <code>required uint32 appid = 1;</code>
       */
      int getAppid();

      /**
       * <code>required uint64 time = 2;</code>
       */
      boolean hasTime();
      /**
       * <code>required uint64 time = 2;</code>
       */
      long getTime();

      /**
       * <code>required bytes v = 3;</code>
       */
      boolean hasV();
      /**
       * <code>required bytes v = 3;</code>
       */
      com.google.protobuf.ByteString getV();

      /**
       * <code>required bytes echostr = 4;</code>
       */
      boolean hasEchostr();
      /**
       * <code>required bytes echostr = 4;</code>
       */
      com.google.protobuf.ByteString getEchostr();

      /**
       * <code>required bytes sign = 5;</code>
       */
      boolean hasSign();
      /**
       * <code>required bytes sign = 5;</code>
       */
      com.google.protobuf.ByteString getSign();

      /**
       * <code>optional uint32 ip = 6;</code>
       */
      boolean hasIp();
      /**
       * <code>optional uint32 ip = 6;</code>
       */
      int getIp();
    }
    /**
     * Protobuf type {@code ReqPkg.Header}
     */
    public static final class Header extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ReqPkg.Header)
        HeaderOrBuilder {
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Header defaultInstance;
      public static Header getDefaultInstance() {
        return defaultInstance;
      }

      public Header getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                appid_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                time_ = input.readUInt64();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                v_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                echostr_ = input.readBytes();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                sign_ = input.readBytes();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                ip_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Req.internal_static_ReqPkg_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Req.internal_static_ReqPkg_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Req.ReqPkg.Header.class, Req.ReqPkg.Header.Builder.class);
      }

      public static com.google.protobuf.Parser<Header> PARSER =
          new com.google.protobuf.AbstractParser<Header>() {
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int APPID_FIELD_NUMBER = 1;
      private int appid_;
      /**
       * <code>required uint32 appid = 1;</code>
       */
      public boolean hasAppid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 appid = 1;</code>
       */
      public int getAppid() {
        return appid_;
      }

      public static final int TIME_FIELD_NUMBER = 2;
      private long time_;
      /**
       * <code>required uint64 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }

      public static final int V_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString v_;
      /**
       * <code>required bytes v = 3;</code>
       */
      public boolean hasV() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes v = 3;</code>
       */
      public com.google.protobuf.ByteString getV() {
        return v_;
      }

      public static final int ECHOSTR_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString echostr_;
      /**
       * <code>required bytes echostr = 4;</code>
       */
      public boolean hasEchostr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes echostr = 4;</code>
       */
      public com.google.protobuf.ByteString getEchostr() {
        return echostr_;
      }

      public static final int SIGN_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString sign_;
      /**
       * <code>required bytes sign = 5;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes sign = 5;</code>
       */
      public com.google.protobuf.ByteString getSign() {
        return sign_;
      }

      public static final int IP_FIELD_NUMBER = 6;
      private int ip_;
      /**
       * <code>optional uint32 ip = 6;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 ip = 6;</code>
       */
      public int getIp() {
        return ip_;
      }

      private void initFields() {
        appid_ = 0;
        time_ = 0L;
        v_ = com.google.protobuf.ByteString.EMPTY;
        echostr_ = com.google.protobuf.ByteString.EMPTY;
        sign_ = com.google.protobuf.ByteString.EMPTY;
        ip_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasAppid()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasV()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEchostr()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSign()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, appid_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt64(2, time_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, v_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, echostr_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, sign_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeUInt32(6, ip_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, appid_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(2, time_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, v_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, echostr_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, sign_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(6, ip_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Req.ReqPkg.Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Req.ReqPkg.Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Req.ReqPkg.Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Req.ReqPkg.Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Req.ReqPkg.Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Req.ReqPkg.Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Req.ReqPkg.Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Req.ReqPkg.Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Req.ReqPkg.Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Req.ReqPkg.Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Req.ReqPkg.Header prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ReqPkg.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ReqPkg.Header)
          Req.ReqPkg.HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Req.internal_static_ReqPkg_Header_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Req.internal_static_ReqPkg_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Req.ReqPkg.Header.class, Req.ReqPkg.Header.Builder.class);
        }

        // Construct using Req.ReqPkg.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          appid_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          time_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          v_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          echostr_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          sign_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          ip_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Req.internal_static_ReqPkg_Header_descriptor;
        }

        public Req.ReqPkg.Header getDefaultInstanceForType() {
          return Req.ReqPkg.Header.getDefaultInstance();
        }

        public Req.ReqPkg.Header build() {
          Req.ReqPkg.Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Req.ReqPkg.Header buildPartial() {
          Req.ReqPkg.Header result = new Req.ReqPkg.Header(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.appid_ = appid_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.time_ = time_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.v_ = v_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.echostr_ = echostr_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.sign_ = sign_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.ip_ = ip_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Req.ReqPkg.Header) {
            return mergeFrom((Req.ReqPkg.Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Req.ReqPkg.Header other) {
          if (other == Req.ReqPkg.Header.getDefaultInstance()) return this;
          if (other.hasAppid()) {
            setAppid(other.getAppid());
          }
          if (other.hasTime()) {
            setTime(other.getTime());
          }
          if (other.hasV()) {
            setV(other.getV());
          }
          if (other.hasEchostr()) {
            setEchostr(other.getEchostr());
          }
          if (other.hasSign()) {
            setSign(other.getSign());
          }
          if (other.hasIp()) {
            setIp(other.getIp());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasAppid()) {
            
            return false;
          }
          if (!hasTime()) {
            
            return false;
          }
          if (!hasV()) {
            
            return false;
          }
          if (!hasEchostr()) {
            
            return false;
          }
          if (!hasSign()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Req.ReqPkg.Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Req.ReqPkg.Header) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int appid_ ;
        /**
         * <code>required uint32 appid = 1;</code>
         */
        public boolean hasAppid() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 appid = 1;</code>
         */
        public int getAppid() {
          return appid_;
        }
        /**
         * <code>required uint32 appid = 1;</code>
         */
        public Builder setAppid(int value) {
          bitField0_ |= 0x00000001;
          appid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 appid = 1;</code>
         */
        public Builder clearAppid() {
          bitField0_ = (bitField0_ & ~0x00000001);
          appid_ = 0;
          onChanged();
          return this;
        }

        private long time_ ;
        /**
         * <code>required uint64 time = 2;</code>
         */
        public boolean hasTime() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint64 time = 2;</code>
         */
        public long getTime() {
          return time_;
        }
        /**
         * <code>required uint64 time = 2;</code>
         */
        public Builder setTime(long value) {
          bitField0_ |= 0x00000002;
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 time = 2;</code>
         */
        public Builder clearTime() {
          bitField0_ = (bitField0_ & ~0x00000002);
          time_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString v_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes v = 3;</code>
         */
        public boolean hasV() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bytes v = 3;</code>
         */
        public com.google.protobuf.ByteString getV() {
          return v_;
        }
        /**
         * <code>required bytes v = 3;</code>
         */
        public Builder setV(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          v_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes v = 3;</code>
         */
        public Builder clearV() {
          bitField0_ = (bitField0_ & ~0x00000004);
          v_ = getDefaultInstance().getV();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString echostr_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes echostr = 4;</code>
         */
        public boolean hasEchostr() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required bytes echostr = 4;</code>
         */
        public com.google.protobuf.ByteString getEchostr() {
          return echostr_;
        }
        /**
         * <code>required bytes echostr = 4;</code>
         */
        public Builder setEchostr(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          echostr_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes echostr = 4;</code>
         */
        public Builder clearEchostr() {
          bitField0_ = (bitField0_ & ~0x00000008);
          echostr_ = getDefaultInstance().getEchostr();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString sign_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes sign = 5;</code>
         */
        public boolean hasSign() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required bytes sign = 5;</code>
         */
        public com.google.protobuf.ByteString getSign() {
          return sign_;
        }
        /**
         * <code>required bytes sign = 5;</code>
         */
        public Builder setSign(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          sign_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes sign = 5;</code>
         */
        public Builder clearSign() {
          bitField0_ = (bitField0_ & ~0x00000010);
          sign_ = getDefaultInstance().getSign();
          onChanged();
          return this;
        }

        private int ip_ ;
        /**
         * <code>optional uint32 ip = 6;</code>
         */
        public boolean hasIp() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional uint32 ip = 6;</code>
         */
        public int getIp() {
          return ip_;
        }
        /**
         * <code>optional uint32 ip = 6;</code>
         */
        public Builder setIp(int value) {
          bitField0_ |= 0x00000020;
          ip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 ip = 6;</code>
         */
        public Builder clearIp() {
          bitField0_ = (bitField0_ & ~0x00000020);
          ip_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ReqPkg.Header)
      }

      static {
        defaultInstance = new Header(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ReqPkg.Header)
    }

    public interface ReqInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ReqPkg.ReqInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required uint32 id = 1;</code>
       */
      int getId();

      /**
       * <code>required bytes url = 2;</code>
       */
      boolean hasUrl();
      /**
       * <code>required bytes url = 2;</code>
       */
      com.google.protobuf.ByteString getUrl();

      /**
       * <code>required bytes deviceid = 3;</code>
       */
      boolean hasDeviceid();
      /**
       * <code>required bytes deviceid = 3;</code>
       */
      com.google.protobuf.ByteString getDeviceid();
    }
    /**
     * Protobuf type {@code ReqPkg.ReqInfo}
     */
    public static final class ReqInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ReqPkg.ReqInfo)
        ReqInfoOrBuilder {
      // Use ReqInfo.newBuilder() to construct.
      private ReqInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ReqInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ReqInfo defaultInstance;
      public static ReqInfo getDefaultInstance() {
        return defaultInstance;
      }

      public ReqInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ReqInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readUInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                url_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                deviceid_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Req.internal_static_ReqPkg_ReqInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Req.internal_static_ReqPkg_ReqInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Req.ReqPkg.ReqInfo.class, Req.ReqPkg.ReqInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<ReqInfo> PARSER =
          new com.google.protobuf.AbstractParser<ReqInfo>() {
        public ReqInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ReqInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int URL_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString url_;
      /**
       * <code>required bytes url = 2;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes url = 2;</code>
       */
      public com.google.protobuf.ByteString getUrl() {
        return url_;
      }

      public static final int DEVICEID_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString deviceid_;
      /**
       * <code>required bytes deviceid = 3;</code>
       */
      public boolean hasDeviceid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes deviceid = 3;</code>
       */
      public com.google.protobuf.ByteString getDeviceid() {
        return deviceid_;
      }

      private void initFields() {
        id_ = 0;
        url_ = com.google.protobuf.ByteString.EMPTY;
        deviceid_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUrl()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDeviceid()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, url_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, deviceid_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, url_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, deviceid_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Req.ReqPkg.ReqInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Req.ReqPkg.ReqInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Req.ReqPkg.ReqInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Req.ReqPkg.ReqInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Req.ReqPkg.ReqInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ReqPkg.ReqInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ReqPkg.ReqInfo)
          Req.ReqPkg.ReqInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Req.internal_static_ReqPkg_ReqInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Req.internal_static_ReqPkg_ReqInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Req.ReqPkg.ReqInfo.class, Req.ReqPkg.ReqInfo.Builder.class);
        }

        // Construct using Req.ReqPkg.ReqInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          url_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          deviceid_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Req.internal_static_ReqPkg_ReqInfo_descriptor;
        }

        public Req.ReqPkg.ReqInfo getDefaultInstanceForType() {
          return Req.ReqPkg.ReqInfo.getDefaultInstance();
        }

        public Req.ReqPkg.ReqInfo build() {
          Req.ReqPkg.ReqInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Req.ReqPkg.ReqInfo buildPartial() {
          Req.ReqPkg.ReqInfo result = new Req.ReqPkg.ReqInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.url_ = url_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.deviceid_ = deviceid_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Req.ReqPkg.ReqInfo) {
            return mergeFrom((Req.ReqPkg.ReqInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Req.ReqPkg.ReqInfo other) {
          if (other == Req.ReqPkg.ReqInfo.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasUrl()) {
            setUrl(other.getUrl());
          }
          if (other.hasDeviceid()) {
            setDeviceid(other.getDeviceid());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasUrl()) {
            
            return false;
          }
          if (!hasDeviceid()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Req.ReqPkg.ReqInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Req.ReqPkg.ReqInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>required uint32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required uint32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString url_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes url = 2;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes url = 2;</code>
         */
        public com.google.protobuf.ByteString getUrl() {
          return url_;
        }
        /**
         * <code>required bytes url = 2;</code>
         */
        public Builder setUrl(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes url = 2;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000002);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString deviceid_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes deviceid = 3;</code>
         */
        public boolean hasDeviceid() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bytes deviceid = 3;</code>
         */
        public com.google.protobuf.ByteString getDeviceid() {
          return deviceid_;
        }
        /**
         * <code>required bytes deviceid = 3;</code>
         */
        public Builder setDeviceid(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          deviceid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes deviceid = 3;</code>
         */
        public Builder clearDeviceid() {
          bitField0_ = (bitField0_ & ~0x00000004);
          deviceid_ = getDefaultInstance().getDeviceid();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ReqPkg.ReqInfo)
      }

      static {
        defaultInstance = new ReqInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ReqPkg.ReqInfo)
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Req.ReqPkg.Header header_;
    /**
     * <code>required .ReqPkg.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ReqPkg.Header header = 1;</code>
     */
    public Req.ReqPkg.Header getHeader() {
      return header_;
    }
    /**
     * <code>required .ReqPkg.Header header = 1;</code>
     */
    public Req.ReqPkg.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    public static final int REQINFO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString reqinfo_;
    /**
     * <code>required bytes reqinfo = 2;</code>
     *
     * <pre>
     *AES���ܺ��ReqInfo
     * </pre>
     */
    public boolean hasReqinfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes reqinfo = 2;</code>
     *
     * <pre>
     *AES���ܺ��ReqInfo
     * </pre>
     */
    public com.google.protobuf.ByteString getReqinfo() {
      return reqinfo_;
    }

    private void initFields() {
      header_ = Req.ReqPkg.Header.getDefaultInstance();
      reqinfo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqinfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, reqinfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, reqinfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Req.ReqPkg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Req.ReqPkg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Req.ReqPkg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Req.ReqPkg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Req.ReqPkg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Req.ReqPkg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Req.ReqPkg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Req.ReqPkg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Req.ReqPkg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Req.ReqPkg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Req.ReqPkg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqPkg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqPkg)
        Req.ReqPkgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Req.internal_static_ReqPkg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Req.internal_static_ReqPkg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Req.ReqPkg.class, Req.ReqPkg.Builder.class);
      }

      // Construct using Req.ReqPkg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = Req.ReqPkg.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        reqinfo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Req.internal_static_ReqPkg_descriptor;
      }

      public Req.ReqPkg getDefaultInstanceForType() {
        return Req.ReqPkg.getDefaultInstance();
      }

      public Req.ReqPkg build() {
        Req.ReqPkg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Req.ReqPkg buildPartial() {
        Req.ReqPkg result = new Req.ReqPkg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqinfo_ = reqinfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Req.ReqPkg) {
          return mergeFrom((Req.ReqPkg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Req.ReqPkg other) {
        if (other == Req.ReqPkg.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasReqinfo()) {
          setReqinfo(other.getReqinfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasReqinfo()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Req.ReqPkg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Req.ReqPkg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Req.ReqPkg.Header header_ = Req.ReqPkg.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Req.ReqPkg.Header, Req.ReqPkg.Header.Builder, Req.ReqPkg.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Req.ReqPkg.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Builder setHeader(Req.ReqPkg.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Builder setHeader(
          Req.ReqPkg.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Builder mergeHeader(Req.ReqPkg.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != Req.ReqPkg.Header.getDefaultInstance()) {
            header_ =
              Req.ReqPkg.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = Req.ReqPkg.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Req.ReqPkg.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      public Req.ReqPkg.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .ReqPkg.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Req.ReqPkg.Header, Req.ReqPkg.Header.Builder, Req.ReqPkg.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Req.ReqPkg.Header, Req.ReqPkg.Header.Builder, Req.ReqPkg.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString reqinfo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes reqinfo = 2;</code>
       *
       * <pre>
       *AES���ܺ��ReqInfo
       * </pre>
       */
      public boolean hasReqinfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes reqinfo = 2;</code>
       *
       * <pre>
       *AES���ܺ��ReqInfo
       * </pre>
       */
      public com.google.protobuf.ByteString getReqinfo() {
        return reqinfo_;
      }
      /**
       * <code>required bytes reqinfo = 2;</code>
       *
       * <pre>
       *AES���ܺ��ReqInfo
       * </pre>
       */
      public Builder setReqinfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqinfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes reqinfo = 2;</code>
       *
       * <pre>
       *AES���ܺ��ReqInfo
       * </pre>
       */
      public Builder clearReqinfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqinfo_ = getDefaultInstance().getReqinfo();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqPkg)
    }

    static {
      defaultInstance = new ReqPkg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqPkg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqPkg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqPkg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqPkg_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqPkg_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqPkg_ReqInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqPkg_ReqInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\treq.proto\"\314\001\n\006ReqPkg\022\036\n\006header\030\001 \002(\0132\016" +
      ".ReqPkg.Header\022\017\n\007reqinfo\030\002 \002(\014\032[\n\006Heade" +
      "r\022\r\n\005appid\030\001 \002(\r\022\014\n\004time\030\002 \002(\004\022\t\n\001v\030\003 \002(" +
      "\014\022\017\n\007echostr\030\004 \002(\014\022\014\n\004sign\030\005 \002(\014\022\n\n\002ip\030\006" +
      " \001(\r\0324\n\007ReqInfo\022\n\n\002id\030\001 \002(\r\022\013\n\003url\030\002 \002(\014" +
      "\022\020\n\010deviceid\030\003 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ReqPkg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqPkg_descriptor,
        new java.lang.String[] { "Header", "Reqinfo", });
    internal_static_ReqPkg_Header_descriptor =
      internal_static_ReqPkg_descriptor.getNestedTypes().get(0);
    internal_static_ReqPkg_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqPkg_Header_descriptor,
        new java.lang.String[] { "Appid", "Time", "V", "Echostr", "Sign", "Ip", });
    internal_static_ReqPkg_ReqInfo_descriptor =
      internal_static_ReqPkg_descriptor.getNestedTypes().get(1);
    internal_static_ReqPkg_ReqInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqPkg_ReqInfo_descriptor,
        new java.lang.String[] { "Id", "Url", "Deviceid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
