package udp_demo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rsp.proto

public final class Rsp {
  private Rsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RspPkgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RspPkg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required uint32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>required bytes msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>required bytes msg = 2;</code>
     */
    com.google.protobuf.ByteString getMsg();

    /**
     * <code>required bytes echostr = 3;</code>
     */
    boolean hasEchostr();
    /**
     * <code>required bytes echostr = 3;</code>
     */
    com.google.protobuf.ByteString getEchostr();

    /**
     * <code>required .RspPkg.RspInfo infos = 4;</code>
     */
    boolean hasInfos();
    /**
     * <code>required .RspPkg.RspInfo infos = 4;</code>
     */
    Rsp.RspPkg.RspInfo getInfos();
    /**
     * <code>required .RspPkg.RspInfo infos = 4;</code>
     */
    Rsp.RspPkg.RspInfoOrBuilder getInfosOrBuilder();
  }
  /**
   * Protobuf type {@code RspPkg}
   */
  public static final class RspPkg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RspPkg)
      RspPkgOrBuilder {
    // Use RspPkg.newBuilder() to construct.
    private RspPkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RspPkg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RspPkg defaultInstance;
    public static RspPkg getDefaultInstance() {
      return defaultInstance;
    }

    public RspPkg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RspPkg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              echostr_ = input.readBytes();
              break;
            }
            case 34: {
              Rsp.RspPkg.RspInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = infos_.toBuilder();
              }
              infos_ = input.readMessage(Rsp.RspPkg.RspInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(infos_);
                infos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rsp.internal_static_RspPkg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rsp.internal_static_RspPkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Rsp.RspPkg.class, Rsp.RspPkg.Builder.class);
    }

    public static com.google.protobuf.Parser<RspPkg> PARSER =
        new com.google.protobuf.AbstractParser<RspPkg>() {
      public RspPkg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RspPkg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RspPkg> getParserForType() {
      return PARSER;
    }

    public interface RspInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:RspPkg.RspInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required uint32 id = 1;</code>
       */
      int getId();

      /**
       * <code>required bytes url = 2;</code>
       */
      boolean hasUrl();
      /**
       * <code>required bytes url = 2;</code>
       */
      com.google.protobuf.ByteString getUrl();

      /**
       * <code>required uint32 urltype = 3;</code>
       */
      boolean hasUrltype();
      /**
       * <code>required uint32 urltype = 3;</code>
       */
      int getUrltype();

      /**
       * <code>required uint32 eviltype = 4;</code>
       */
      boolean hasEviltype();
      /**
       * <code>required uint32 eviltype = 4;</code>
       */
      int getEviltype();
    }
    /**
     * Protobuf type {@code RspPkg.RspInfo}
     */
    public static final class RspInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:RspPkg.RspInfo)
        RspInfoOrBuilder {
      // Use RspInfo.newBuilder() to construct.
      private RspInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RspInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RspInfo defaultInstance;
      public static RspInfo getDefaultInstance() {
        return defaultInstance;
      }

      public RspInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RspInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readUInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                url_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                urltype_ = input.readUInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                eviltype_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rsp.internal_static_RspPkg_RspInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rsp.internal_static_RspPkg_RspInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Rsp.RspPkg.RspInfo.class, Rsp.RspPkg.RspInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<RspInfo> PARSER =
          new com.google.protobuf.AbstractParser<RspInfo>() {
        public RspInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RspInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RspInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int URL_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString url_;
      /**
       * <code>required bytes url = 2;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes url = 2;</code>
       */
      public com.google.protobuf.ByteString getUrl() {
        return url_;
      }

      public static final int URLTYPE_FIELD_NUMBER = 3;
      private int urltype_;
      /**
       * <code>required uint32 urltype = 3;</code>
       */
      public boolean hasUrltype() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 urltype = 3;</code>
       */
      public int getUrltype() {
        return urltype_;
      }

      public static final int EVILTYPE_FIELD_NUMBER = 4;
      private int eviltype_;
      /**
       * <code>required uint32 eviltype = 4;</code>
       */
      public boolean hasEviltype() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 eviltype = 4;</code>
       */
      public int getEviltype() {
        return eviltype_;
      }

      private void initFields() {
        id_ = 0;
        url_ = com.google.protobuf.ByteString.EMPTY;
        urltype_ = 0;
        eviltype_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUrl()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUrltype()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEviltype()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, url_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeUInt32(3, urltype_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeUInt32(4, eviltype_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, url_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, urltype_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, eviltype_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Rsp.RspPkg.RspInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Rsp.RspPkg.RspInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Rsp.RspPkg.RspInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Rsp.RspPkg.RspInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Rsp.RspPkg.RspInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code RspPkg.RspInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:RspPkg.RspInfo)
          Rsp.RspPkg.RspInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Rsp.internal_static_RspPkg_RspInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Rsp.internal_static_RspPkg_RspInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Rsp.RspPkg.RspInfo.class, Rsp.RspPkg.RspInfo.Builder.class);
        }

        // Construct using Rsp.RspPkg.RspInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          url_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          urltype_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          eviltype_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Rsp.internal_static_RspPkg_RspInfo_descriptor;
        }

        public Rsp.RspPkg.RspInfo getDefaultInstanceForType() {
          return Rsp.RspPkg.RspInfo.getDefaultInstance();
        }

        public Rsp.RspPkg.RspInfo build() {
          Rsp.RspPkg.RspInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Rsp.RspPkg.RspInfo buildPartial() {
          Rsp.RspPkg.RspInfo result = new Rsp.RspPkg.RspInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.url_ = url_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.urltype_ = urltype_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.eviltype_ = eviltype_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Rsp.RspPkg.RspInfo) {
            return mergeFrom((Rsp.RspPkg.RspInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Rsp.RspPkg.RspInfo other) {
          if (other == Rsp.RspPkg.RspInfo.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasUrl()) {
            setUrl(other.getUrl());
          }
          if (other.hasUrltype()) {
            setUrltype(other.getUrltype());
          }
          if (other.hasEviltype()) {
            setEviltype(other.getEviltype());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasUrl()) {
            
            return false;
          }
          if (!hasUrltype()) {
            
            return false;
          }
          if (!hasEviltype()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Rsp.RspPkg.RspInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Rsp.RspPkg.RspInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>required uint32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required uint32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString url_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes url = 2;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes url = 2;</code>
         */
        public com.google.protobuf.ByteString getUrl() {
          return url_;
        }
        /**
         * <code>required bytes url = 2;</code>
         */
        public Builder setUrl(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes url = 2;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000002);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }

        private int urltype_ ;
        /**
         * <code>required uint32 urltype = 3;</code>
         */
        public boolean hasUrltype() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required uint32 urltype = 3;</code>
         */
        public int getUrltype() {
          return urltype_;
        }
        /**
         * <code>required uint32 urltype = 3;</code>
         */
        public Builder setUrltype(int value) {
          bitField0_ |= 0x00000004;
          urltype_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 urltype = 3;</code>
         */
        public Builder clearUrltype() {
          bitField0_ = (bitField0_ & ~0x00000004);
          urltype_ = 0;
          onChanged();
          return this;
        }

        private int eviltype_ ;
        /**
         * <code>required uint32 eviltype = 4;</code>
         */
        public boolean hasEviltype() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required uint32 eviltype = 4;</code>
         */
        public int getEviltype() {
          return eviltype_;
        }
        /**
         * <code>required uint32 eviltype = 4;</code>
         */
        public Builder setEviltype(int value) {
          bitField0_ |= 0x00000008;
          eviltype_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 eviltype = 4;</code>
         */
        public Builder clearEviltype() {
          bitField0_ = (bitField0_ & ~0x00000008);
          eviltype_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:RspPkg.RspInfo)
      }

      static {
        defaultInstance = new RspInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:RspPkg.RspInfo)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required uint32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>required bytes msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes msg = 2;</code>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    public static final int ECHOSTR_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString echostr_;
    /**
     * <code>required bytes echostr = 3;</code>
     */
    public boolean hasEchostr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes echostr = 3;</code>
     */
    public com.google.protobuf.ByteString getEchostr() {
      return echostr_;
    }

    public static final int INFOS_FIELD_NUMBER = 4;
    private Rsp.RspPkg.RspInfo infos_;
    /**
     * <code>required .RspPkg.RspInfo infos = 4;</code>
     */
    public boolean hasInfos() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .RspPkg.RspInfo infos = 4;</code>
     */
    public Rsp.RspPkg.RspInfo getInfos() {
      return infos_;
    }
    /**
     * <code>required .RspPkg.RspInfo infos = 4;</code>
     */
    public Rsp.RspPkg.RspInfoOrBuilder getInfosOrBuilder() {
      return infos_;
    }

    private void initFields() {
      status_ = 0;
      msg_ = com.google.protobuf.ByteString.EMPTY;
      echostr_ = com.google.protobuf.ByteString.EMPTY;
      infos_ = Rsp.RspPkg.RspInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEchostr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInfos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfos().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, echostr_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, infos_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, echostr_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, infos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Rsp.RspPkg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rsp.RspPkg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rsp.RspPkg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rsp.RspPkg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rsp.RspPkg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rsp.RspPkg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Rsp.RspPkg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Rsp.RspPkg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Rsp.RspPkg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rsp.RspPkg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Rsp.RspPkg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RspPkg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RspPkg)
        Rsp.RspPkgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rsp.internal_static_RspPkg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rsp.internal_static_RspPkg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Rsp.RspPkg.class, Rsp.RspPkg.Builder.class);
      }

      // Construct using Rsp.RspPkg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        echostr_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (infosBuilder_ == null) {
          infos_ = Rsp.RspPkg.RspInfo.getDefaultInstance();
        } else {
          infosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rsp.internal_static_RspPkg_descriptor;
      }

      public Rsp.RspPkg getDefaultInstanceForType() {
        return Rsp.RspPkg.getDefaultInstance();
      }

      public Rsp.RspPkg build() {
        Rsp.RspPkg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Rsp.RspPkg buildPartial() {
        Rsp.RspPkg result = new Rsp.RspPkg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.echostr_ = echostr_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (infosBuilder_ == null) {
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Rsp.RspPkg) {
          return mergeFrom((Rsp.RspPkg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Rsp.RspPkg other) {
        if (other == Rsp.RspPkg.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasEchostr()) {
          setEchostr(other.getEchostr());
        }
        if (other.hasInfos()) {
          mergeInfos(other.getInfos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        if (!hasEchostr()) {
          
          return false;
        }
        if (!hasInfos()) {
          
          return false;
        }
        if (!getInfos().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Rsp.RspPkg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Rsp.RspPkg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <code>required uint32 status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required uint32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes msg = 2;</code>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>required bytes msg = 2;</code>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString echostr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes echostr = 3;</code>
       */
      public boolean hasEchostr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes echostr = 3;</code>
       */
      public com.google.protobuf.ByteString getEchostr() {
        return echostr_;
      }
      /**
       * <code>required bytes echostr = 3;</code>
       */
      public Builder setEchostr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        echostr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes echostr = 3;</code>
       */
      public Builder clearEchostr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        echostr_ = getDefaultInstance().getEchostr();
        onChanged();
        return this;
      }

      private Rsp.RspPkg.RspInfo infos_ = Rsp.RspPkg.RspInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Rsp.RspPkg.RspInfo, Rsp.RspPkg.RspInfo.Builder, Rsp.RspPkg.RspInfoOrBuilder> infosBuilder_;
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public boolean hasInfos() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Rsp.RspPkg.RspInfo getInfos() {
        if (infosBuilder_ == null) {
          return infos_;
        } else {
          return infosBuilder_.getMessage();
        }
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Builder setInfos(Rsp.RspPkg.RspInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          infos_ = value;
          onChanged();
        } else {
          infosBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Builder setInfos(
          Rsp.RspPkg.RspInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          infos_ = builderForValue.build();
          onChanged();
        } else {
          infosBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Builder mergeInfos(Rsp.RspPkg.RspInfo value) {
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              infos_ != Rsp.RspPkg.RspInfo.getDefaultInstance()) {
            infos_ =
              Rsp.RspPkg.RspInfo.newBuilder(infos_).mergeFrom(value).buildPartial();
          } else {
            infos_ = value;
          }
          onChanged();
        } else {
          infosBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = Rsp.RspPkg.RspInfo.getDefaultInstance();
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Rsp.RspPkg.RspInfo.Builder getInfosBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getInfosFieldBuilder().getBuilder();
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      public Rsp.RspPkg.RspInfoOrBuilder getInfosOrBuilder() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilder();
        } else {
          return infos_;
        }
      }
      /**
       * <code>required .RspPkg.RspInfo infos = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Rsp.RspPkg.RspInfo, Rsp.RspPkg.RspInfo.Builder, Rsp.RspPkg.RspInfoOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Rsp.RspPkg.RspInfo, Rsp.RspPkg.RspInfo.Builder, Rsp.RspPkg.RspInfoOrBuilder>(
                  getInfos(),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RspPkg)
    }

    static {
      defaultInstance = new RspPkg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RspPkg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RspPkg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RspPkg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RspPkg_RspInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RspPkg_RspInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trsp.proto\"\235\001\n\006RspPkg\022\016\n\006status\030\001 \002(\r\022\013" +
      "\n\003msg\030\002 \002(\014\022\017\n\007echostr\030\003 \002(\014\022\036\n\005infos\030\004 " +
      "\002(\0132\017.RspPkg.RspInfo\032E\n\007RspInfo\022\n\n\002id\030\001 " +
      "\002(\r\022\013\n\003url\030\002 \002(\014\022\017\n\007urltype\030\003 \002(\r\022\020\n\010evi" +
      "ltype\030\004 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RspPkg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RspPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RspPkg_descriptor,
        new java.lang.String[] { "Status", "Msg", "Echostr", "Infos", });
    internal_static_RspPkg_RspInfo_descriptor =
      internal_static_RspPkg_descriptor.getNestedTypes().get(0);
    internal_static_RspPkg_RspInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RspPkg_RspInfo_descriptor,
        new java.lang.String[] { "Id", "Url", "Urltype", "Eviltype", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
